export const GETPRODUCTS = 'GETPRODUCTS';
export const CREATEPRODUCT = 'CREATEPRODUCT';
export const GETPRODUCT = 'GETPRODUCT';
export const UPDATEPRODUCT = 'UPDATEPRODUCT';
export const DELETEPRODUCT = 'DELETEPRODUCT';

